version: '3.8'

services:
  db:
    image: postgres:15
    container_name: order_db
    restart: always
    environment:
      POSTGRES_DB: order_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./seed/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql